### ISSUE TITLE
when minValue and maxValue differ too small；

### ISSUE THREAD

**Issue by tmeme** [CuriousSolutions/AnyPicker#6]
```
$("#ip-de").AnyPicker(
				{
					mode: "datetime",
					viewSections:
					{
						header: [],
						contentTop: [],
						contentBottom: [],
						footer: ["cancelButton", "headerTitle","setButton"]
					},
					i18n:{
						headerTitle: "select",
						setButton: "sure",
						nowButton: "Now",
						cancelButton: "cancel"
					},
					layout: "fixed",

					dateTimeFormat: "yyyy-MM-dd",
					theme:"iOS",
					minValue: new Date("2016-05-06"),
					maxValue: new Date(new Date("2016-05-06").getTime()+1000*60*60*24*7)
				});
```
![image](https://cloud.githubusercontent.com/assets/7479046/15073982/00714704-13cf-11e6-9f56-3e1bf5c31d15.png)

**Comment by nehakadam** [comment]
Thank you for reporting a bug! Please download a latest version and check.

**Comment by tmeme** [comment]
fixed

**Comment by tmeme** [comment]
update to  latest version
when value change;
0undefinedundefinedundefined-undefinedundefinedundefined-undefinedundefinedundefined 
![image](https://cloud.githubusercontent.com/assets/7479046/15209099/d83ba4a4-1861-11e6-828a-2b270d8d7c16.png)

**Comment by nehakadam** [comment]
I could not reproduce error. Please check parameters of `setOutput` callback function in Documentation. 

If error is not solved then post entire code the way you posted at first, so that I can check for a particular test case. Also mention OS, browser and browser version on which you are testing.

**Comment by tmeme** [comment]
```
<script type="text/javascript">
		
			$(document).ready(function()
			{

				$("#ip-de").AnyPicker(
						{
							mode: "datetime",
							viewSections:
							{
								header: ["cancelButton", "headerTitle","setButton"],
								contentTop: [],
								contentBottom: [],
								footer: ["cancelButton", "headerTitle","setButton"]
							},
							i18n:{
								headerTitle: "选择预约时间",
								setButton: "确定",
								nowButton: "Now",
								cancelButton: "取消"
							},
							layout: "fixed",

							dateTimeFormat: "yyyy-MM-dd",
							theme:"iOS",
							//rowHeight:108*(window.innerWidth || document.documentElement.clientWidth)/1242,
							minValue: new Date(),
							maxValue: new Date(new Date().getTime()+1000*60*60*24*7),
							setOutput:function(val){
								console.log(val);
								if(!(new Date(val).getTime()) ){
									var s = new Date(new Date().getTime()+1000*60*60*24*1),
											year = s.getFullYear(),
											m = s.getMonth()+1 >10 ? s.getMonth()+1 : "0"+(s.getMonth()+1),
											d = s.getDay();
									val = year +"-"+m+"-"+d;
								}
								if(new Date(val).getTime() ){

								}

							}
						});
			});

		</script>
```
```
<button  id="ip-de" readonly>button</button>
```
![image](https://cloud.githubusercontent.com/assets/7479046/15498714/54a2563a-21d3-11e6-8624-6d659f7c08ab.png)

**Comment by tmeme** [comment]
```
<script type="text/javascript">
		
			$(document).ready(function()
			{

				$("#ip-de").AnyPicker(
						{
							mode: "datetime",
							viewSections:
							{
								header: ["cancelButton", "headerTitle","setButton"],
								contentTop: [],
								contentBottom: [],
								footer: ["cancelButton", "headerTitle","setButton"]
							}, 
							layout: "fixed",

							dateTimeFormat: "yyyy-MM-dd",
							theme:"iOS",
							//rowHeight:108*(window.innerWidth || document.documentElement.clientWidth)/1242,
							minValue: new Date(),
							maxValue: new Date(new Date().getTime()+1000*60*60*24*7),
							setOutput:function(val){
								console.log(val);
								if(!(new Date(val).getTime()) ){
									var s = new Date(new Date().getTime()+1000*60*60*24*1),
											year = s.getFullYear(),
											m = s.getMonth()+1 >10 ? s.getMonth()+1 : "0"+(s.getMonth()+1),
											d = s.getDay();
									val = year +"-"+m+"-"+d;
								}
								if(new Date(val).getTime() ){

								}

							}
						});
			});

		</script>
```
```
<button  id="ip-de" readonly>button</button>
```
![image](https://cloud.githubusercontent.com/assets/7479046/15499121/16ba96b4-21d5-11e6-8aa5-86008e4f7af0.png)

**Comment by nehakadam** [comment]
There is an issue with this when non-input element is used. If `<input type="text" id="ip-de" readonly>` is used then this issue is not detected.

**Comment by nehakadam** [comment]
I know it's too late but posting comment so that it may help someone else.

Please go through [NonInputElement.htm](https://github.com/CuriousSolutions/AnyPicker/blob/master/demo/AnyPicker-Common-NonInputElement.htm) as an example of implementing AnyPicker with Non Input Element.
